Gem::Specification.new do |s|
  s.name        = 'flowroute_numbers'
  s.version     = '1.0'
  s.summary     = 'flowroute_numbers'
  s.description = 'This API SDK was generated by Flowroute & APIMATIC'
  s.authors     = ["Flowroute", "Sean Hsieh", "APIMATIC", "Zeeshan Ejaz Bhatti"]
  s.email       = 'sean@flowroute.com'
  s.homepage    = 'https://www.flowroute.com'
  s.license     = 'MIT'
  
  s.add_dependency('unirest', '~> 1.1.2')
  s.required_ruby_version = '~> 2.0'

  s.files       = Dir['{bin,lib,man,test,spec}/**/*', 'README*', 'LICENSE*']  
  s.require_paths = ['lib']
  
end